[package]
name = "chal"
version = "0.1.0"
authors = ["Simon Renblad <simon.renblad@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
